services:
  postgres-service:
    image: postgres:17.5-alpine3.21
    hostname: postgres-service
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=training
    networks:
      users-network:
      #- ipv4_address: 192.168.10.11
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d:ro
  users-service:
    image: landrzejewski/users-service
    restart: on-failure
    depends_on:
      - postgres-service
    deploy:
      replicas: 3
    networks:
      users-network:
  proxy:
    image: nginx:1.28-alpine
    restart: on-failure
    depends_on:
      - users-service
    ports:
      - "192.168.1.100:8080:80"
      - "192.168.1.100:8081:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./proxy:/etc/nginx/conf.d:ro
    networks:
      users-network:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    networks:
      users-network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
networks:
  users-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
